### ISSUE TITLE
Explode Thoth repo in a Thoth organization

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Thoth#121]
I would like to switch from a mono repo structure to an organisation structure.

This would help maintain older version of the library and make the docs support version history.

**Comment by rfrerebe** [comment]
Hello,

What about having a single organisation with fable-compiler ?

For example [Fable.Powerpack](https://github.com/fable-compiler/fable-powerpack/issues/63) is dead and replaced by a [Fable.Fetch without FetchAs](https://github.com/fable-compiler/fable-fetch/blob/master/src/Fetch.fs#L358-L368) currently because it depends of Thoth.

My 2 cents : Fable is small, let's keep everything simple

**Comment by MangelMaxime** [comment]
I don't want to host it under Fable org because I need to create several repos and also want to have the repos follow a certain architecture so documentation and future updates/upgrade are easier.

I don't see much benefit on hosting then under Fable.

All the projects under Fable organization are maintain by the Fable maintainers while Thoth projects are maintains by me.

In the past, we had a discussion between the Fable maintainers and decided to not host too much project under the org or only the official library that we supports. Because, if the main maintainer of the library stop maintaining the library it would be on us to do the maintenance stuff and we can't.
