### ISSUE TITLE
Use own parser to fuse Thoth.Json and Thoth.Json.Net

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#128]
Now that Thoth.Json 3 beta is published it's time to think of v4 😸 

It's great that Thoth can be used both in JS and .NET. However, the fact that there're are two packages for this complicates maintenance and confuses users, as other cross-platform packages only have one published version (see #124).

AFAIK. the only reason for the two packages is to use `JSON.parse` in JS and Newtonsoft.Json in .NET. This seems sensible because parsing JSON looks complicated. However, [this JSON parser by Jon Harrop](https://twitter.com/FableCompiler/status/1090691264981417985) is just a few lines of code and it's compatible with Fable. We can adapt it and make it a bit more performant (don't split the string, etc).

Also, if we control the DSL we don't need so many helpers (isNumber, isNull...) and transforming to string after encoding shouldn't be too difficult either.

What do you think @MangelMaxime?

**Comment by MangelMaxime** [comment]
We not only need a parser but a writer too.

We also need to see how performant it is for big JSON parsing/writing. Thoth.Json v3 isn't yet released in stable version so it's should be possible to include the parser change in it.

And of course, I would love to see `Thoth.Json.Net` deprecated and make user life simpler :) This is probably the last big issues with Thoth.Json at the moment.

I will give it a try today and see how it goes. Will keep inform :)

**Comment by danyx23** [comment]
I think unifying the JS and .NET Thoth stuff would be great. We have moved away from the recommended #ifdef solution since it confused ionide and didn't play well with nuget packages that were to be used both by fable and .net projects.

My personal thinking (first roughly expressed in #45) is to create a new nuget package that contains only interface definitions for an IDecoder<'jsonType> and IEncoder<'jsonType> that can parse primitive values and is generic over the json implementation and then have concrete implementations (that also provide a fromString and toString respectively) for the different underlying json library.

So roughly:
```fsharp
type IJsonDecodeProvider<'JsonType> =
  abstract isNumber : 'JsonType-> bool
  abstract asFloat : 'JsonType-> float
  // ..

type Decoder <'T, 'JsonType> = IJsonDecodeProvider<'JsonType> -> string -> 'JsonType -> Result<'T, DecoderError<'JsonType>>
```

And then e.g. the newtonsoft implementation would be
```fsharp
open Newtonsoft.Json.Linq
let NewtonsoftJsonProvider =
  { new IJsonDecodeProvider<JToken> =
      member this.isNumber (token : JToken) = token.Type = JTokenType.Float || token.Type = JTokenType.Integer
      // ...
  }

let fromString = ...
```

I wanted to try this out in a fork for a long time but haven't gotten around to it yet. The nice thing would be that if all you want to do is declare Encoders/Decoders you only need to reference the library that declares the interfaces, only when you want to actually serialize/deserialize do you have to decide on a concrete library

**Comment by MangelMaxime** [comment]
So you would expose `Decode.fromString`, `Decode.Auto.fromString`, `Encode.toString`, `Encode.Auto.ToString` only from the "implementation" packages?

**Comment by danyx23** [comment]
That was my Idea, yes (but I don't use Auto decoders so can't comment on how feasibly/desirable that is for this). Maybe there is a good reason to add this to the interface as well, but it looks to me like this is not necessary for the base library to already be useful for declaring coders in libraries

**Comment by MangelMaxime** [comment]
I will try to play with both of your ideas and see how to goes.

And nothing prevents a mix of both . Using a "contracts" library and showing that you can use any JSON parser in it even yours for whatever reason (slim dependencies perhaps).

**Comment by kspeakman** [comment]
I've been exploring using a single serializer for both sides, but I think our team is going to let that dream die. Some things just don't make sense to deal with in client-side codecs because JS can't handle them anyway. I'd rather make a separate client-side type and be forced to think about the right representation for JS (even JS written in F# :) ) to avoid footguns.

We use auto-codecs almost exclusively. In our situation parsing flexibility is not used, so maintaining manual codecs has extra cost with zero benefit.

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
