### ISSUE TITLE
On serializing/deserializing a DateTime, "Kind" information is lost and is set to UTC

### ISSUE THREAD

**Issue by sachabroute** [MangelMaxime/Thoth#156]
When serializing a DateTime CEST, on deserializing we lose the "Kind" information and it is set by default to UTC.

Client:
![image](https://user-images.githubusercontent.com/3247529/61869465-fa2f8580-aedb-11e9-9715-5b8c0c334807.png)

Server: 
![image](https://user-images.githubusercontent.com/3247529/61869497-09aece80-aedc-11e9-84ea-29f9ff220d9c.png)

**Comment by MangelMaxime** [comment]
By default, we transfer UTC over the JSON because your client and server can be on a different timezone. I think this is what most JSON serialize do but can be wrong.

In general, if you need a specific `DateTime` handler, you should write your own.

It's also possible that `DateTimeOffset` is a solution for that too, I don't know. Handling date is really complex :)

**Comment by sachabroute** [comment]
Makes sense, I was also thinking it might have been done deliberately as server should always have the UTC time.
However it seems there is some ambiguity as to other JSON serializers do since I think Newtonsoft.Json does deserialize the Kind properly, but Microsoft's don't.
Maybe this would deserve some kind of note somewhere?

**Comment by MangelMaxime** [comment]
> Maybe this could deserve some kind of note somewhere?

We can add that to the doc comment [here](https://github.com/thoth-org/Thoth.Json/blob/master/src/Encode.fs#L302) and [here](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Encode.fs#L183).

Note that the projects are in a separate repo.

The split of this repo isn't complete yet.

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
