### ISSUE TITLE
Q: Transparently support erased single-case DUs on .NET side

### ISSUE THREAD

**Issue by et1975** [MangelMaxime/Thoth#158]
Trying to use Thoth.Json on a model I'm sharing with Saturn backend. So I plugged in Thoth as `IJsonSerializer` and everything seems to be working, however, I'm trying to optimize the use of single-case DUs and I'm applying `[<Erase>]` on the Fable side and `[<Struct>]` on the .NET side but that doesn't survive the roundtrip:

```fsharp
#if FABLE_COMPILER
type NoAlloc = Fable.Core.EraseAttribute
#else
type NoAlloc = StructAttribute
#endif

[<NoAlloc>]
type AttributeId = AttributeId of Guid
```

I guess I need to plug some "extra" encoder/decoder to tell Thoth to unwrap single-case DUs?

**Comment by MangelMaxime** [comment]
Hello,

what's the JSON output of `.Net side` when applying the encoder to `[<Struct>]`?

**Comment by et1975** [comment]
Struct types retain the shape of their non-struct types, so currently it looks like any other DU:
```json
["AttributeId","00000000-0000-0000-0000-000000000000"]
```

**Comment by MangelMaxime** [comment]
Ok, so I need to do more test on my side because I don't see why it's not working by default. I guess the `Struct` attributes is doing something to the representation of the DUs and/or break the reflection code. I never worked with `Struct` before and so we don't have tests for them.

> Basically it seems an unnecessary overhead to put the single-case DU's case into the payload, but I understand it may be surprising to someone.

This is not the first time someone brought this subject about JSON representation.

It has been brought when Fable.Converter was a thing (Fable 1).

And at F# Exchange, I had a discussion about it too.

I never really looked into this issue because it just impacts the JSON representation and keeps it "constant". But yes, it's making it a bit longer than needed for single-case DUs.

The complaints come when people do "strict" domain modelling like:

```fs
type AttributeId = AttributeId of Guid

type Email = Email of string
```

because from what I understand they consider it an alias to `string` in the case of Email for example.

I several ways to activate this simplifier solution:

- Use a dedicated attributes `[<SimpleRepresentation>]` It's just an example name, this would just be an attribute for us to detect on the DU but it would not be an alias to `Struct` or `Erase`. People would have to write `[<SimpleRepresentation; Struct>]` is they want both behaviours.
- Have an argument to auto coders in order to activate this behaviour
- Have this behaviour available by default

What do you think?

**Comment by et1975** [comment]
Probably better to have an option somewhere.

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
