### ISSUE TITLE
Consider creating an interface for use with libraries for both .net core and fable

### ISSUE THREAD

**Issue by danyx23** [MangelMaxime/Thoth#45]
I really like the Thoth library and use it in a SAFE project, but one thing that is a bit annoying is that if you want to create a nuget package that uses Thoth and that can be used from both normal .NET and a Fable project, you currently have to create two versions of the library: one that references Fable.Json and one that references Fable.Json.Net.

I recently thought about ways to solve this and had the idea might help with this: what if a third library could be created that defines the type signatures for the various Thoth types (errors, ...) and two interface types that define the encoder/decoder functions. It would have to be generic over the Json type (Newtonsoft one vs obj). Then the Fable.Json.Net could implement this interface using Newtonsoft and the Fable version could implement it using the Fable way.

A library could then define functions that expect a type implementing this interface and only reference this new, third library and thus be used by both Fable code and regular .NET code.

This is just a wild idea at the moment and I am probably missing something - do you think this is worth investigating more?

**Comment by MangelMaxime** [comment]
I had this idea in the past but kind of discarded it because I wasn't able to find a nice way to do it.
We need to consider the generated code, a bit the performance even if we aren't heavily focused on them.

Also, the runtimes being different we kind of abuse some specials things from one or another (especially on the Fable side :man_shrugging: )

Also, you don't have to create two versions of your library. You can use compiler directives.

```fs
#if FABLE_COMPILER
// Fable code
#else
// .Net code
#endif
```

I tried to use the directives in Thoth.Json at first, but it was a mess because of the different types etc. But in a library because the exposed API by Thoth.Json and Thoth.Json.Net is the same then you can easily use it. Indeed you just need to encapsulate the `open` statements.

```fs
#if FABLE_COMPILER
open Thoth.Json
#else
open Thoth.Json.Net
#endif
```

This is the reason why I considered it to be ok like that. 

I tried to explain you my point of view and how I came up to the current structure. Of course, I am open to discussion and suggestion :)

**Comment by MangelMaxime** [comment]
I will close this issue, feel free to re-open if you have new ideas/questions.

**Comment by danyx23** [comment]
Of course, thank you for you elaborations and sorry I didn't reply ealrier! I'll see how it goes with this in practice and come back when I have more concrete ideas. Thanks!
