### ISSUE TITLE
Holding a key pressed does not result with repeating it, as expected

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Thoth#81]
1. Move focus to the Name input or Description text area
2. Press and hold any alphabetical key
3. Result: it's not repeated, only single character appears

![image](https://user-images.githubusercontent.com/873919/49029923-fade1380-f1b6-11e8-8a94-68a3608a337f.png)

**Comment by MangelMaxime** [comment]
Indeed...

I guess I am doing something that react do not like. But I wonder what 🤔

**Comment by AkosLukacs** [comment]
Strange, on windows, it does work in all of my browsers:
 - Vivaldi (chromium-based); No react devtools
 - Chrome canary; With react devtools
 - Firefox; No react devtools
 - Edge 😨 
 - IE11 😱 

Tried clicking into the input, tab-ing, shift-tab, and all works for me.

Can you check other fable / react apps?

**Comment by MangelMaxime** [comment]
@AkosLukacs Gaves me the idea to test different applications.

So I tested the following for repeating keys:

- [FormBuilder demo](https://mangelmaxime.github.io/Thoth/elmish/FormBuilder.html) - FormBuilder lib
- [Toast builder](https://mangelmaxime.github.io/Thoth/elmish/toast_demo.html) - Manual way
- [Fulma demo](https://mangelmaxime.github.io/fulma-demo/#question/1) - Manual way
- VSCode editor, the desktop app
- TextEdit, the desktop app

And none of this applications supports repeating keys. So I believe this is the OS that prevent it.

And it make sense because because on OS X you can hold a key to access the special version of it.

![2018-11-27 11 30 43](https://user-images.githubusercontent.com/4760796/49075840-ef7efc80-f237-11e8-92c4-9dc13d5d5174.gif)

@vasily-kirichenko are you using a OS X?

**Comment by vasily-kirichenko** [comment]
@MangelMaxime yes, it was on OS X in Chrome. I've just tested in Chrome on Windows - it works.

**Comment by MangelMaxime** [comment]
Ok, I will close this issue as this is not related to the library.
