### ISSUE TITLE
Merge the documentation engine with the static-web-generator

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#86]
It'd be great to reuse the work done by @MangelMaxime with Thoth documentation for other Fable websites, by merging it with [the static-web-generator](https://github.com/fable-compiler/static-web-generator). This would probably involve:

- Move most of the generic helpers to [a shared file](https://github.com/fable-compiler/static-web-generator/blob/master/src/Helpers.fs) so it's easier to reuse them.
- Replace the Handlebars templates [with React frames](https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/src/components/Frame.fs) for simplicity.
- Simplify the build process, using the new fable-splitter and just npm scripts.

What do you think? cc @whitetigle

**Comment by MangelMaxime** [comment]
Current implementation of the Thoth documentation is a bit hacky.

Especially:
- [Code highlight](https://github.com/MangelMaxime/Thoth/blob/master/docs/src/js/utils.js#L44-L67) because I am using [Code Lightner](https://github.com/MangelMaxime/Code-Lightner) in order to provide good F# highlight and it's needs to use `promise` based API when markdown-it doesn't support promise. So I am parsing the generated html string to capture fsharp code blocks.
- [Table of Content](https://github.com/MangelMaxime/Thoth/blob/master/docs/src/Renderer/Page.fs#L49-L103) generation has been creating by parsing the html string again because it was easier for me than creating a plugin for markdown-it but we should create a markdown-it plugin for that :)

**Comment by whitetigle** [comment]
I would definitely love it! 😁 The Ultimate doc generator!

**Comment by alfonsogarciacaro** [comment]
Ok, let's close this for now and we'll see later if we can recycle some parts :)
