### ISSUE TITLE
FormBuilder docs has some issues

### ISSUE THREAD

**Issue by isaacabraham** [MangelMaxime/Thoth#91]
1. Include whatever `open` statements are required, or fully qualify with `FormBuilder` - otherwise people will get stuck as e.g. with default SAFE template, `Form` will resolve to the HTML form (I opened `Thoth.Elmish` and fully qualified from there on).
2. the `getLanguages` bit is a bit confusing - I didn't realise that's taken from the sample above, perhaps point to that.
3. the `getLanguages` code could be simplified - either `return!` but actually why even have one function that just calls the other one and does nothing more?
4. In section 6 there is no such type as `FormSate`, it should be I think `FormBuilder.Types.State`.
5. Also section 6 the references to `formState` in the call to `Form.render` should be (I think) `model.FormState`, and not `formState` - otherwise it references the "global" form state that gets created right at the start and nothing works correctly :-)

**Comment by MangelMaxime** [comment]
About `getLanguages` I added this to the documentation:

```fs
let getLanguages =
    promise {
        // We are calling directly `FakeServer.getLanguages` but in a
        // real case you would make a server request
        return! FakeServer.getLanguages ()
    }
```

My idea was to make sure the user understand that the data should be fetched from the server. If the applicartion already know the data, we can use `WithValues` directly instead of  `WithValuesFromServer`.

All the others point will be fixed in the next docs release. I am fixing the build process right now ...
